apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: automerge-pipeline
spec:
  params:
  - name: github-secret
    type: string
  - name: commit-name
    type: string
    description: the GitHub name to use on the commit
  - name: commit-email
    type: string
    description: the GitHub email to use on the commit
  resources: 
  - name: source-repo
    type: git
  - name: pr
    type: pullRequest
  tasks:
  - name: do-this-first
    taskRef:
      name: automerge-task
    resources:
      inputs:
      - name: git-source
        resource: source-repo
      - name: pull-request
        resource: pr
    params:
    - name: github-secret
      value: $(params.github-secret)
    - name: commit-name
      value: $(params.commit-name)
    - name: commit-email
      value: $(params.commit-email)